<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

In [1]:
#Before I forget, 
import numpy as np

# Subsetting: Indexing and Slicing

To summarize the words in the heading, 
- **Subsetting**: Select data from a list or array (for this course)
    - **Indexing**: Is a form of subsetting. It means chosing just one element.
    - **Slicing**: Is also a form of subsetting. It means chosing a range of elements.  

## Lists & Arrays in 1D | Subsetting & Indexing

To begin this, let us create a list (and an array) for us to play around with. 

In [3]:
py_list = ["Old","Mcdonald","had","a","farm","ee","aai","eey","aay","oo"]
np_array = np.array(py_list)

#We can assume x=py_list or x=np_array

Now the following results will work with both py_list and np_array. 

**Indexing**
|Syntax|Result|Output|Note|
|---|---|---|---|
|```x[0]```|First Element|```'Old'```|Remember, 0 base indexing|
|```x[-1]```|Last element|```"oo"```|Remember, -1 base indexing for negative numbers|

**Slicing**
|Syntax|Result|Output|Note|
|---|---|---|---|
|```x[0:4]```|Index 0 to 3 (Position 1 to 4)|```['Old','Mcdonald','had','a']```|$4-0=4$ elements|
|```x[4:7]```|Index 4 to 6 (Position 5 to 7)|```['farm','ee','aai']```|$7-4=3$ elements|
|```x[1:7:2]```|Index 1 to 6 in steps of 2 (Position 2,4,6)|```['Mcdonald','a','ee']```|$7-1=6$, every 2nd element|
|```x[7:]```|Index 7 to the end (Position 8 to 10)|```['eey','aay','oo']```|```len(x)```$-7$ elements|
|```x[:7]```|Index 0 to 6 (Position 1 to 7)|```['Old','Mcdonald','had','a','farm','ee','aai']```|Gives $7-0=7$ elements|
|```x[6:1:-1]```|Index 6 to 2, reversed (Position 7 to 2)|```['aai','ee','farm','a','had']```|Gives $6-1 =5$ elements|
|```x[::-1]```|Reverse the list|```['oo','aay','eey','aai','ee','farm','a','had','Mcdonald','Old']```|Magic|


TLDR: ```[i:j]``` slice implies $j-i$ elements will be printed. 

In [5]:
x=np_array
print(x[0:4], x[4:7] , x[1:7:2] , x[7:] , x[:7] , x[6:1:-1] , x[::-1])

['Old' 'Mcdonald' 'had' 'a'] ['farm' 'ee' 'aai'] ['Mcdonald' 'a' 'ee'] ['eey' 'aay' 'oo'] ['Old' 'Mcdonald' 'had' 'a' 'farm' 'ee' 'aai'] ['aai' 'ee' 'farm' 'a' 'had'] ['oo' 'aay' 'eey' 'aai' 'ee' 'farm' 'a' 'had' 'Mcdonald' 'Old']


## Arrays only | Subsetting by masking

Masking is a fun thing we can do only with NumPy arrays. 

In [6]:
#Creating another list, because mcdonald is tiring
numpy_array = np.array([2,4,6,8,9,24,3278234242344])
mask = numpy_array>95
mask

array([False, False, False, False, False, False,  True])

Basically masks assigns Truthy and Falsy values to elements in the list. We can just get all the True elements printed. 

In [7]:
numpy_array[mask]

array([3278234242344], dtype=int64)

All this can be actually done in one line, 

In [9]:
numpy_array[numpy_array<84]

array([ 2,  4,  6,  8,  9, 24], dtype=int64)

### Other masking operations

**Inverting**

To do this, we can use the Bitwise Not operator, ```~```

In [10]:
numpy_array[~(numpy_array<84)]

array([3278234242344], dtype=int64)

**Combining masks with AND**

To do this, we can use the Bitwise And operator, ```&```

In [14]:
numpy_array[(numpy_array<5) & (numpy_array>5000)] #we expect to see an empty list

array([], dtype=int64)

In [13]:
numpy_array[(numpy_array<5000) & (numpy_array>5)]

array([ 6,  8,  9, 24], dtype=int64)

**Combining Masks with OR**

To do this, we can use the Bitwise Or operator, ```|```

In [15]:
numpy_array[(numpy_array<5)|(numpy_array>5000)]

array([            2,             4, 3278234242344], dtype=int64)

## Lists & Arrays in 2D | Indexing & Slicing

## Growing lists

# Some loose ends

## Tuples

## Be VERY careful when copying