<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

Data structures ofc.

In [1]:
import numpy as np #incase i forget

# Lists, Arrays & Dictionaries

We can store the same data in three different formats: **Python Lists**, **Numpy Array**, **Dictionary**. 

## Let’s compare

**Python Lists**

In [2]:
py_s_name = ["Batman", "Flash", "Superman"] #always a DC stan
py_r_name = ["Bruce Wayne", "Barry Allen", "Clark Kent"]

As seen above, to store two sets of data, we can use two python lists. Notice: need square brackets to denote lists. 

**Numpy Arrays**

In [4]:
np_s_name = np.array(["Batman", "Flash", "Superman"])
np_r_name = np.array(["Bruce Wayne", "Barry Allen", "Clark Kent"])

As seen above, we need to call the attribute ```array``` from numpy to create an array. It has parantheses with square brakets inside to hold the stuff. 

**Dictionary**

In [6]:
sup_info ={
    "Batman":"Bruce Wayne",
    "Flash":"Barry Allen",
    "Superman":"Clark Kent"
}

As seen above, we can create one dictionary to hold all the information needed instead of creating two separate lists or arrays. 
The structure is ```<key>:<value>```.

## Accessing data from a list (or array)

Python lists and numpy arrays are **0 indexed**, means the positive indexing starts from 0 and not 1. The negative indexing starts from -1.
The positive indexing goes from left to right, whereas the negative indexing goes from right to left. 

In [9]:
print(py_s_name[1])
print(np_r_name[2])
print(np_s_name[-2])

Flash
Clark Kent
Flash


The syntax is ```list_name[index_number]```. Remember: This works for both lists and arrays. 

## Accessing data from a dictionary

Now for the dictionary, we can directly call the key and it will give us the value.

In [10]:
sup_info["Flash"]

'Barry Allen'

In [11]:
sup_info["Barry Allen"]

KeyError: 'Barry Allen'

As seen above, we cannot call the value, just the key.

We can get all the info we want by using the attribute ```keys``` and ```values```.

In [12]:
sup_info.keys()

dict_keys(['Batman', 'Flash', 'Superman'])

In [13]:
sup_info.values()

dict_values(['Bruce Wayne', 'Barry Allen', 'Clark Kent'])

## Higher dimensional lists

Creating lists inside lists results in the formation of **higher dimensional lists**. So instead of creating two separate lists, 

In [15]:
py_sup_info=[["Batman","Bruce Wayne"],["Flash","Barry Allen"],["Superman","Clark Kent"]]

# 2 Lists vs. Arrays

## 2.1 Size

In [16]:
py_list_2D = [[1,"A"],[2,"B"],[3,"C"],[4,"D"],[5,"E"],[6,"F"], [7,"G"],[8,"H"],[9,"I"],[10,"J"]]
np_array_2D = np.array(py_list_2D)

The length of both lists are the same, which can be checked using the ```len()``` function. 

In [17]:
print(len(py_list_2D),len(np_array_2D))

10 10


However the added benefit of using arrays is that it also tells us about the shape of the list/array. 

In [20]:
np_array_2D.shape

(10, 2)

In [22]:
omega=np.array([[['a']]])
omega.shape

(1, 1, 1)

So ```shape``` tells us the the number of elements in the highest dimension list, followed by the number of elementes in the lower dimension list, followed by number of elements in the lowest dimensions list. 

## Arrays are fussy about type

In [23]:
alpha=np.array([['a'],['b','c']])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

And the above case will not arise because numpy only accepts homogenous arrays. 

Clearly, array is always fussy about the types. If there is one string, everything will be converted to string in that array. 

In [24]:
py_list=[1,2,3,4,'monke']
np_list=np.array(py_list)
print(py_list)
print(np_list)

[1, 2, 3, 4, 'monke']
['1' '2' '3' '4' 'monke']


## Adding a number

In [25]:
py_list = [1,2,3,4,5,6,7,8,9,10]
np_list = np.array(py_list)
#these lists will be used for all the maths section now.

We can add a number to each element in the list **only in array and not in lists**.

In [26]:
py_list+10

TypeError: can only concatenate list (not "int") to list

In [27]:
np_list+10

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

## Adding another list

In [29]:
py_list2 =[11,12,13,14,15,16,17,18,19,20]
np_list2 = np.array(py_list2)

Now we can add these around.

In [30]:
py_list+py_list2 #this is concatenation

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [31]:
np_list+np_list2 #this is element wise addition

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

As shown above, lists treat ```+``` as a concatenation operation, whereas arrays treat them as element wise addition operation. This also means if the **arrays** are unequal size, then the cannot be added. 

## Multiplying by a Number

In [32]:
py_list*2 #this is the number of concatenation 

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [33]:
np_list*2 #this is element wise multiplication

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

Lists treat ```*``` as how many times they will concatenate with themselves, wherease array treat them as element wise multiplication. 

## Squaring

In [35]:
py_list**2 #will not work

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [36]:
np_list**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

There is no meaning of ```**``` for lists, whereas arrays treat them as power operator. 

## Asking questions

In [37]:
py_list ==3

False

There is an output because 3 is not a list. The comparison over here is not of the elements in the list. 

In [38]:
py_list>3 #hence this doesnt work, because this is not a comparison with the list.

TypeError: '>' not supported between instances of 'list' and 'int'

In [39]:
np_list == 3

array([False, False,  True, False, False, False, False, False, False,
       False])

In [40]:
np_list<5

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

Thus, logical operators work with arrays and not with lists. 

## Mathematics

In [41]:
sum(py_list)

55

In [42]:
max(py_list)

10

In [43]:
min(py_list)

1

In [44]:
py_list.sum()

AttributeError: 'list' object has no attribute 'sum'

As seen above, ```sum```, ```min``` and ```max``` are python functions. However, lists do not have any attribute called sum min or max. 

In [45]:
sum(np_list)

55

In [46]:
np_list.sum()

55

In [48]:
np_list.max()

10

In [49]:
np_list.min()

1

In [50]:
np_list.mean()

5.5

In [51]:
np_list.var()

8.25

In [53]:
np_list.std()

2.8722813232690143

Arrays are cool stuff clearly. 